stages:
  - build
  - test
  - deploy

build_backend:
  stage: build
  script:
    - cd backend
    - npm install
    - docker build -t backend .

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - docker build -t frontend .

deploy:
  stage: deploy
  script:
    - docker-compose up -d
